/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeneficioRouteImport } from './routes/beneficio'
import { Route as ContabilidadRouteImport } from './routes/contabilidad'
import { Route as CosechaRouteImport } from './routes/cosecha'
import { Route as CostosRouteImport } from './routes/costos'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as FinanzasRouteImport } from './routes/finanzas'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as LiquidacionRouteImport } from './routes/liquidacion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LotesRouteImport } from './routes/lotes'
import { Route as ProductividadRouteImport } from './routes/productividad'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficioRoute = BeneficioRouteImport.update({
  id: '/beneficio',
  path: '/beneficio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadRoute = ContabilidadRouteImport.update({
  id: '/contabilidad',
  path: '/contabilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const CosechaRoute = CosechaRouteImport.update({
  id: '/cosecha',
  path: '/cosecha',
  getParentRoute: () => rootRouteImport,
} as any)
const CostosRoute = CostosRouteImport.update({
  id: '/costos',
  path: '/costos',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasRoute = FinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidacionRoute = LiquidacionRouteImport.update({
  id: '/liquidacion',
  path: '/liquidacion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LotesRoute = LotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductividadRoute = ProductividadRouteImport.update({
  id: '/productividad',
  path: '/productividad',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beneficio': typeof BeneficioRoute
  '/contabilidad': typeof ContabilidadRoute
  '/cosecha': typeof CosechaRoute
  '/costos': typeof CostosRoute
  '/equipo': typeof EquipoRoute
  '/finanzas': typeof FinanzasRoute
  '/historial': typeof HistorialRoute
  '/liquidacion': typeof LiquidacionRoute
  '/login': typeof LoginRoute
  '/lotes': typeof LotesRoute
  '/productividad': typeof ProductividadRoute
  '/ventas': typeof VentasRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficio': typeof BeneficioRoute
  '/contabilidad': typeof ContabilidadRoute
  '/cosecha': typeof CosechaRoute
  '/costos': typeof CostosRoute
  '/equipo': typeof EquipoRoute
  '/finanzas': typeof FinanzasRoute
  '/historial': typeof HistorialRoute
  '/liquidacion': typeof LiquidacionRoute
  '/login': typeof LoginRoute
  '/lotes': typeof LotesRoute
  '/productividad': typeof ProductividadRoute
  '/ventas': typeof VentasRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beneficio': typeof BeneficioRoute
  '/contabilidad': typeof ContabilidadRoute
  '/cosecha': typeof CosechaRoute
  '/costos': typeof CostosRoute
  '/equipo': typeof EquipoRoute
  '/finanzas': typeof FinanzasRoute
  '/historial': typeof HistorialRoute
  '/liquidacion': typeof LiquidacionRoute
  '/login': typeof LoginRoute
  '/lotes': typeof LotesRoute
  '/productividad': typeof ProductividadRoute
  '/ventas': typeof VentasRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beneficio'
    | '/contabilidad'
    | '/cosecha'
    | '/costos'
    | '/equipo'
    | '/finanzas'
    | '/historial'
    | '/liquidacion'
    | '/login'
    | '/lotes'
    | '/productividad'
    | '/ventas'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficio'
    | '/contabilidad'
    | '/cosecha'
    | '/costos'
    | '/equipo'
    | '/finanzas'
    | '/historial'
    | '/liquidacion'
    | '/login'
    | '/lotes'
    | '/productividad'
    | '/ventas'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/beneficio'
    | '/contabilidad'
    | '/cosecha'
    | '/costos'
    | '/equipo'
    | '/finanzas'
    | '/historial'
    | '/liquidacion'
    | '/login'
    | '/lotes'
    | '/productividad'
    | '/ventas'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeneficioRoute: typeof BeneficioRoute
  ContabilidadRoute: typeof ContabilidadRoute
  CosechaRoute: typeof CosechaRoute
  CostosRoute: typeof CostosRoute
  EquipoRoute: typeof EquipoRoute
  FinanzasRoute: typeof FinanzasRoute
  HistorialRoute: typeof HistorialRoute
  LiquidacionRoute: typeof LiquidacionRoute
  LoginRoute: typeof LoginRoute
  LotesRoute: typeof LotesRoute
  ProductividadRoute: typeof ProductividadRoute
  VentasRoute: typeof VentasRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficio': {
      id: '/beneficio'
      path: '/beneficio'
      fullPath: '/beneficio'
      preLoaderRoute: typeof BeneficioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad': {
      id: '/contabilidad'
      path: '/contabilidad'
      fullPath: '/contabilidad'
      preLoaderRoute: typeof ContabilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosecha': {
      id: '/cosecha'
      path: '/cosecha'
      fullPath: '/cosecha'
      preLoaderRoute: typeof CosechaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costos': {
      id: '/costos'
      path: '/costos'
      fullPath: '/costos'
      preLoaderRoute: typeof CostosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas': {
      id: '/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof FinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidacion': {
      id: '/liquidacion'
      path: '/liquidacion'
      fullPath: '/liquidacion'
      preLoaderRoute: typeof LiquidacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotes': {
      id: '/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof LotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productividad': {
      id: '/productividad'
      path: '/productividad'
      fullPath: '/productividad'
      preLoaderRoute: typeof ProductividadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeneficioRoute: BeneficioRoute,
  ContabilidadRoute: ContabilidadRoute,
  CosechaRoute: CosechaRoute,
  CostosRoute: CostosRoute,
  EquipoRoute: EquipoRoute,
  FinanzasRoute: FinanzasRoute,
  HistorialRoute: HistorialRoute,
  LiquidacionRoute: LiquidacionRoute,
  LoginRoute: LoginRoute,
  LotesRoute: LotesRoute,
  ProductividadRoute: ProductividadRoute,
  VentasRoute: VentasRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
